-- account_products.sql

create table accounts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  individuals_id bigint references public.individuals not null,
  account_products_id bigint references public.account_products not null,
  token uuid default uuid_generate_v4(),
  updated_at timestamp with time zone,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  active boolean not null,
  config varchar,
  start_date date not null,
  end_date date,
  name varchar
);